#!/usr/bin/env php

<?php

require __DIR__.'/bootstrap/app.php';

use Downloader\Downloader;
use Symfony\Component\Console\Application;

$app = new Application('Github repos downloader', '0.0.1');
// Config related commands

$app->add(new Downloader());

$app->setAutoExit(true);
$app->run();
